### ISSUE TITLE
Will not install

### ISSUE THREAD

**Issue by john-clark** [velocityzen/homebridge-platform-zwave#2]
USER: root
DIR: /usr/lib
CMD: npm --no-update-notifier install --unsafe-perm homebridge-platform-zwave@latest

> openzwave-shared@1.5.10 preinstall /usr/lib/node_modules/homebridge-platform-zwave/node_modules/openzwave-shared
> node lib/install-ozw.js

> openzwave-shared@1.5.10 install /usr/lib/node_modules/homebridge-platform-zwave/node_modules/openzwave-shared
> node-gyp rebuild

make: Entering directory '/usr/lib/node_modules/homebridge-platform-zwave/node_modules/openzwave-shared/build'
  CXX(target) Release/obj.target/openzwave_shared/src/callbacks.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-config.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-driver.o
  CXX(target) Release/obj.target/openzwave_shared/src/openzwave-groups.o
../src/openzwave-groups.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE OZW::OZW::GetAssociationsInstances(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/openzwave-groups.cc:98:4: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::IntegerFactory<v8::Integer>::return_t)’
    );
    ^
In file included from ../src/openzwave.hpp:27:0,
                 from ../src/openzwave-groups.cc:18:
/root/.cache/node-gyp/13.1.0/include/node/v8.h:3424:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/root/.cache/node-gyp/13.1.0/include/node/v8.h:3424:37: note:   candidate expects 3 arguments, 2 provided
/root/.cache/node-gyp/13.1.0/include/node/v8.h:3427:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/root/.cache/node-gyp/13.1.0/include/node/v8.h:3427:37: note:   candidate expects 3 arguments, 2 provided
../src/openzwave-groups.cc:102:4: error: no matching function for call to ‘v8::Object::Set(v8::Local<v8::String>, Nan::imp::IntegerFactory<v8::Integer>::return_t)’
    );
    ^
In file included from ../src/openzwave.hpp:27:0,
                 from ../src/openzwave-groups.cc:18:
/root/.cache/node-gyp/13.1.0/include/node/v8.h:3424:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/root/.cache/node-gyp/13.1.0/include/node/v8.h:3424:37: note:   candidate expects 3 arguments, 2 provided
/root/.cache/node-gyp/13.1.0/include/node/v8.h:3427:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/root/.cache/node-gyp/13.1.0/include/node/v8.h:3427:37: note:   candidate expects 3 arguments, 2 provided
../src/openzwave-groups.cc:104:44: error: no matching function for call to ‘v8::Array::Set(Nan::imp::IntegerFactory<v8::Integer>::return_t, v8::Local<v8::Object>&)’
    o_assocs->Set(Nan::New<Integer>(i), info);
                                            ^
In file included from ../src/openzwave.hpp:27:0,
                 from ../src/openzwave-groups.cc:18:
/root/.cache/node-gyp/13.1.0/include/node/v8.h:3424:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
                                     ^~~
/root/.cache/node-gyp/13.1.0/include/node/v8.h:3424:37: note:   candidate expects 3 arguments, 2 provided
/root/.cache/node-gyp/13.1.0/include/node/v8.h:3427:37: note: candidate: v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)
   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
                                     ^~~
/root/.cache/node-gyp/13.1.0/include/node/v8.h:3427:37: note:   candidate expects 3 arguments, 2 provided
openzwave_shared.target.mk:146: recipe for target 'Release/obj.target/openzwave_shared/src/openzwave-groups.o' failed
make: *** [Release/obj.target/openzwave_shared/src/openzwave-groups.o] Error 1
make: Leaving directory '/usr/lib/node_modules/homebridge-platform-zwave/node_modules/openzwave-shared/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.9.0-11-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homebridge-platform-zwave/node_modules/openzwave-shared
gyp ERR! node -v v13.1.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! openzwave-shared@1.5.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openzwave-shared@1.5.10 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-17T06_14_47_657Z-debug.log

Command failed. Please review log for details.

**Comment by iamandyogden** [comment]
I'm getting exactly the same error, any update on this?

**Comment by john-clark** [comment]
I was able to get it to install.

`wget http://old.openzwave.com/downloads/openzwave-1.6.1044.tar.gz
tar xzvf openzwave-1.6.1044.tar.gz
cd openzwave-1.6.1044/
make
sudo make install
sudo sed -i '$a LD_LIBRARY_PATH=/usr/local/lib64' /etc/environment
MinOZW /dev/ttyACM1`

This was able to get node-gyp to install correctly.
